GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug

####

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "password": "password",
    "email": "jordan@test.com",
    "name_first": "Jordan",
    "name_last": "Tam"
}

####

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "password": "password",
    "email": "elain@test.com",
    "name_first": "Elain",
    "name_last": "Lau"
}

####

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "jordan@test.com",
    "password": "password"
}

#####

GET http://localhost:3000/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug

####
GET http://localhost:3000/user/profile?u_id=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug


####
PUT http://localhost:3000/user/profile/setname
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug
Content-Type: application/json

{
    "name_first": "Lewis",
    "name_last": "Lee"
}



####
PUT http://localhost:3000/user/profile/setname
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug
Content-Type: application/json

{
    "name_first": "Jordan",
    "name_last": "Tam"
}

####
PUT http://localhost:3000/user/profile/setemail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug
Content-Type: application/json

{
    "email": "jordan@test.com"
}

####

PUT http://localhost:3000/user/profile/sethandle
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug
Content-Type: application/json

{
    "handle_str": "Nleisis"
}

####

##Jordan Create Channel
POST http://localhost:3000/channels/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug
Content-Type: application/json

{
    "name": "Jordan",
    "is_public": true
}

####

## Elain Create Channel
POST http://localhost:3000/channels/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug
Content-Type: application/json

{
    "name": "Elain Channel",
    "is_public": true
}



####

GET http://localhost:3000/channels/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug

####

GET http://localhost:3000/channels/listall
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug

####
GET http://localhost:3000/channel/details?channel_id=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug

####
POST http://localhost:3000/channel/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug
Content-Type: application/json

{
    "channel_id": 5
}

####

POST http://localhost:3000/channel/leave
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug
Content-Type: application/json

{
    "channel_id": 5
}

####
POST http://localhost:3000/channel/addowner
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug
Content-Type: application/json

{
    "channel_id": 4,
    "u_id": 2
}

####
POST http://localhost:3000/channel/removeowner
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug
Content-Type: application/json

{
    "channel_id": 4,
    "u_id": 2
}

####
GET http://localhost:3000/channel/messages?channel_id=4&start=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug
Content-Type: application/json

####
POST http://localhost:3000/message/send
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug
Content-Type: application/json

{
    "channel_id": 4,
    "message": "Hello 3"
}


####
PUT http://localhost:3000/message/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug
Content-Type: application/json

{
    "message_id": 1,
    "message": "Hello Sky"
}

####
DELETE http://localhost:3000/message/remove?message_id=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMjAyODM4MSwiZXhwIjoxNzEyMTE0NzgxfQ.QlKAbCrCw0NPyUXfYnAaoqdPxKd6Tx_NRJmpC2uv1Ug

