GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMTU1MTUxMywiZXhwIjoxNzExNjM3OTEzfQ.jRso5aK4bnQM3IzHB9RtTOR52OcL3dEwUEQP2KYjd70

####

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "password": "password",
    "email": "jordan@test.com",
    "name_first": "Jordan",
    "name_last": "Tam"
}

####

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "password": "password",
    "email": "elain@test.com",
    "name_first": "Elain",
    "name_last": "Lau"
}

####

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "jordan@test.com",
    "password": "password"
}

#####

GET http://localhost:3000/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMTU1MTUxMywiZXhwIjoxNzExNjM3OTEzfQ.jRso5aK4bnQM3IzHB9RtTOR52OcL3dEwUEQP2KYjd70

####
GET http://localhost:3000/user/profile?u_id=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMTU1MTUxMywiZXhwIjoxNzExNjM3OTEzfQ.jRso5aK4bnQM3IzHB9RtTOR52OcL3dEwUEQP2KYjd70


####
PUT http://localhost:3000/user/profile/setname
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMTU1MTUxMywiZXhwIjoxNzExNjM3OTEzfQ.jRso5aK4bnQM3IzHB9RtTOR52OcL3dEwUEQP2KYjd70
Content-Type: application/json

{
    "name_first": "Lewis",
    "name_last": "Lee"
}



####
PUT http://localhost:3000/user/profile/setname
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMTU1MTUxMywiZXhwIjoxNzExNjM3OTEzfQ.jRso5aK4bnQM3IzHB9RtTOR52OcL3dEwUEQP2KYjd70
Content-Type: application/json

{
    "name_first": "Jordan",
    "name_last": "Tam"
}

####
PUT http://localhost:3000/user/profile/setemail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMTU1MTUxMywiZXhwIjoxNzExNjM3OTEzfQ.jRso5aK4bnQM3IzHB9RtTOR52OcL3dEwUEQP2KYjd70
Content-Type: application/json

{
    "email": "jordan@test.com"
}

####

PUT http://localhost:3000/user/profile/sethandle
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMTU1MTUxMywiZXhwIjoxNzExNjM3OTEzfQ.jRso5aK4bnQM3IzHB9RtTOR52OcL3dEwUEQP2KYjd70
Content-Type: application/json

{
    "handle_str": "Nleisis"
}

####

##Jordan Create Channel
POST http://localhost:3000/channels/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMTU1MTUxMywiZXhwIjoxNzExNjM3OTEzfQ.jRso5aK4bnQM3IzHB9RtTOR52OcL3dEwUEQP2KYjd70
Content-Type: application/json

{
    "name": "Jordan",
    "is_public": true
}

####

## Elain Create Channel
POST http://localhost:3000/channels/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjIsIm5hbWVfZmlyc3QiOiJFbGFpbiIsIm5hbWVfbGFzdCI6IkxhdSIsImVtYWlsIjoiZWxhaW5AdGVzdC5jb20iLCJwYXNzd29yZCI6IjVlODg0ODk4ZGEyODA0NzE1MWQwZTU2ZjhkYzYyOTI3NzM2MDNkMGQ2YWFiYmRkNjJhMTFlZjcyMWQxNTQyZDgiLCJjcmVhdGVhdCI6IjE3MTE0ODI5MjY0MjEiLCJpbWciOm51bGwsInVzZXJuYW1lIjpudWxsLCJwZXJtaXNzaW9uX2lkIjoxLCJpYXQiOjE3MTE1NTkxNTYsImV4cCI6MTcxMTY0NTU1Nn0.D1GoA2JK2equkGNDVseHduKVXrEXKS8XbjaK-1MZSvs
Content-Type: application/json

{
    "name": "Elain Channel",
    "is_public": true
}



####

GET http://localhost:3000/channels/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMTgwMTIyMywiZXhwIjoxNzExODg3NjIzfQ.iz8K2k-v9UVCBnM1vmr0Mj0qPrRyA_S5m4rD8W8sCb0

####

GET http://localhost:3000/channels/listall
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMTgwMTIyMywiZXhwIjoxNzExODg3NjIzfQ.iz8K2k-v9UVCBnM1vmr0Mj0qPrRyA_S5m4rD8W8sCb0

####
GET http://localhost:3000/channel/details?channel_id=4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMTgwMTIyMywiZXhwIjoxNzExODg3NjIzfQ.iz8K2k-v9UVCBnM1vmr0Mj0qPrRyA_S5m4rD8W8sCb0

####
POST http://localhost:3000/channel/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMTgwMTIyMywiZXhwIjoxNzExODg3NjIzfQ.iz8K2k-v9UVCBnM1vmr0Mj0qPrRyA_S5m4rD8W8sCb0
Content-Type: application/json

{
    "channel_id": 5
}

####

POST http://localhost:3000/channel/leave
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMTgwMTIyMywiZXhwIjoxNzExODg3NjIzfQ.iz8K2k-v9UVCBnM1vmr0Mj0qPrRyA_S5m4rD8W8sCb0
Content-Type: application/json

{
    "channel_id": 5
}

####
POST http://localhost:3000/channel/addowner
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMTgwMTIyMywiZXhwIjoxNzExODg3NjIzfQ.iz8K2k-v9UVCBnM1vmr0Mj0qPrRyA_S5m4rD8W8sCb0
Content-Type: application/json

{
    "channel_id": 4,
    "u_id": 2
}

####
POST http://localhost:3000/channel/addowner
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3VzZXJfaWQiOjEsIm5hbWVfZmlyc3QiOiJKb3JkYW4iLCJuYW1lX2xhc3QiOiJUYW0iLCJlbWFpbCI6ImpvcmRhbkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiNWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOCIsImNyZWF0ZWF0IjoiMTcxMTQ4Mjg1Njg0NyIsImltZyI6bnVsbCwidXNlcm5hbWUiOm51bGwsInBlcm1pc3Npb25faWQiOjEsImlhdCI6MTcxMTgwMTIyMywiZXhwIjoxNzExODg3NjIzfQ.iz8K2k-v9UVCBnM1vmr0Mj0qPrRyA_S5m4rD8W8sCb0
Content-Type: application/json

{
    "channel_id": 4,
    "u_id": 2
}

